# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # https://nodejs.org/en/about/previous-releases

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: "true"
        token: ${{ secrets.PROTOREPO_ACCESS }}
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Cache bootstrap files
      id: cache-bootstrap
      uses: actions/cache@v3
      with:
        path: |
          internal/.bin
          internal/dprint
        key: ${{ runner.os }}-bootstrap
    
    - run: npm ci
    - run: npm run bootstrap
    - run: npm run gen
    - run: npm run eslint
    - run: npm run format:check
    - run: npm test
